blog_main/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('create_post/', views.PostCreate.as_view()),
    path('tag/<str:slug>/', views.show_tag_posts),
    path('category/<str:slug>/', views.show_category_posts),
    path('<int:pk>/new_comment/', views.addComment),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('', views.PostList.as_view()),
    #path('<int:pk>/', views.single_post_page),
    #path('', views.index),
]

blog_main/blog_main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('', include('single_pages.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_main/single_pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('about_me/', views.about_me),
    path('', views.landing),

]

blog_main/blog/models.py
import os.path

from django.db import models
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from markdownx.utils import markdown


# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog/tag/{self.slug}/'


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog/category/{self.slug}/'

    class Meta:
        verbose_name_plural = 'categories'


class Post(models.Model):
    title = models.CharField(max_length=30)
    content = MarkdownxField()

    hook_msg = models.TextField(blank=True)

    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    attached_file = models.FileField(upload_to='blog/files/%Y/%m/%d/', blank=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    tags = models.ManyToManyField(Tag, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # 모델 methods 정의(override)
    def __str__(self):
        return f'[{self.pk}] [{self.title}] :: {self.author}'

    def get_absolute_url(self):
        return f'/blog/{self.pk}/'

    def get_file_name(self):
        return os.path.basename(self.attached_file.name)

    def get_content_markdown(self):
        return markdown(self.content)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.author}::{self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

blog_main/single_pages/models.py
from django.db import models

# Create your models here.

blog_main/blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

blog_main/blog/views.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.shortcuts import get_object_or_404
from .forms import CommentForm
from .models import Post, Category, Tag


class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'hook_msg', 'head_image', 'attached_file', 'category']

    template_name = 'blog/post_form_update.html'

    def dispatch(self, request, *args, **kwargs):
        current_user = request.user
        if current_user.is_authenticated and current_user == self.get_object().author :
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else :
            raise PermissionDenied


class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'hook_msg', 'head_image', 'attached_file', 'category']

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user

        if current_user.is_authenticated and (current_user.is_superuser or current_user.is_staff):
            form.instance.author = current_user
            return super(PostCreate, self).form_valid(form)
        else:
            return redirect('/blog/')


class PostList(ListView):
    model = Post
    ordering = '-pk'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostList, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['count_posts_without_category'] = Post.objects.filter(category=None).count()
        return context


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostDetail, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['count_posts_without_category'] = Post.objects.filter(category=None).count()
        context['comment_form'] = CommentForm
        return context


def show_category_posts(request, slug):
    if slug == 'no-category':  # 미분류 글 요청
        category = '미분류'
        post_list = Post.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)

    context = {
        'categories': Category.objects.all(),
        'count_posts_without_category': Post.objects.filter(category=None).count(),
        'category': category,
        'post_list': post_list
    }
    return render(request, 'blog/post_list.html', context)


def show_tag_posts(request, slug):
    tag = Tag.objects.get(slug=slug)
    post_list = tag.post_set.all()

    context = {
        'categories': Category.objects.all(),
        'count_posts_without_category': Post.objects.filter(category=None).count(),
        'tag': tag,
        'post_list': post_list
    }
    return render(request, 'blog/post_list.html', context)

def addComment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)

        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
            else:
                return redirect(post.get_absolute_url())
        else:
            raise PermissionDenied

'''
def index(request):
    posts = Post.objects.all().order_by('-pk')

    return render(
        request,
        'blog/post_list.html',
        {
            'posts': posts,
        }
    )


def single_post_page(request, pk):
    post = Post.objects.get(pk=pk)

    return render(
        request,
        'blog/post_detail.html',
        {
            'post': post,
        }
    )
'''

blog_main/single_pages/views.py
from django.shortcuts import render
from blog.models import Post


# Create your views here.


def landing(request):
    recent_posts = Post.objects.order_by('-pk')[:3]
    return render(request, 'single_pages/landing.html',
                  {
                      'recent_posts': recent_posts,
                  })


def about_me(request):
    return render(request, 'single_pages/about_me.html')

blog_main/blog/templates/blog/base.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    {% block title %}
    {% endblock %}
        <link rel="stylesheet" href="{% static 'blog/bootstrap/bootstrap.min.css' %}" media="screen">

    <script src="https://kit.fontawesome.com/726bbd6862.js" crossorigin="anonymous"></script>
</head>

<body>
    {% include 'blog/navbar.html' %}

    <div class="container my-3">
        <div class="row">
            <div class="col-md-8 col-lg-9">
                {% block main_area %}

                {% endblock %}
            </div>

            <div class="col-md-4 col-lg-3">
                <!-- Search Widget -->
                <div class="card my-4">
                    <h5 class="card-header">Search</h5>
                    <div class="card-body">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for...">
                            <span class="input-group-btn">
                                <button class="btn btn-secondary" type="button">Go!</button>
                            </span>
                        </div>
                    </div>
                </div>

                <!-- Categories Widget -->
                <div class="card my-4">
                    <h5 class="card-header">Categories</h5>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <ul class="list-unstyled mb-0">
                                    {% for c in categories %}
                                        <li>
                                            <a href="{{ c.get_absolute_url }}">{{ c.name }} ({{ c.post_set.count }})</a>
                                        </li>
                                    {% endfor %}
                                    <li>
                                        <a href="/blog/category/no-category">미분류 ({{ count_posts_without_category }})</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'blog/footer.html' %}


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

</body>

</html>

blog_main/blog/templates/blog/footer.html
 <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">
                Copyright &copy; Seunghun Park 2022.
            </p>
        </div>
        <!-- /.container -->
    </footer>

blog_main/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
</head>
<body>
    <h1>안녕하세요</h1>
    {% for p in posts %}
    <hr/>
        <h2>{{  p.title }}</h2>
        <h4>{{  p.created_at }}</h4>
        <p>{{ p.content }}</p>
    {% endfor %}
</body>
</html>

blog_main/blog/templates/blog/navbar.html
{% load socialaccount %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/">DjangoBlog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/blog/">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/about_me/">About Me</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Dropdown link
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#" data-toggle="modal" data-target="#loginModal">Log In</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
   <!-- Modal -->
    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="logInModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="loginModalLabel"> <i class="fas fa-sign-in-alt"></i>&nbsp Log In</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6">
                            <a type="button" class="btn btn-outline-dark btn-block btn-sm" href="{% provider_login_url 'google' %}"><i class="fab fa-google"></i>&nbsp&nbsp Log in with Google</a>
                            <a type="button" class="btn btn-outline-dark btn-block btn-sm" href="/accounts/login"><i class="far fa-envelope"></i>&nbsp&nbsp Log in with E-mail</a>
                        </div>
                        <div class="col-md-6">
                            <a type="button" class="btn btn-outline-dark btn-block btn-sm" href="/accounts/signup"><i class="far fa-envelope"></i>&nbsp&nbsp Sign Up with E-mail</a>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

blog_main/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Blog - {{ post.title }}</title>
{% endblock %}

    {% block main_area %}
      <!-- Post Content Column -->
      <div class="col-lg-8">

        {% if user.is_authenticated and user == post.author %}
            <a href="/blog/update_post/{{ post.pk }}">Update Post</a>
        {% endif %}

        <!-- Title -->
        <h1 class="mt-4">{{ post.title }}</h1>

        <!-- Author -->
        <p class="lead">
          by
          <a href="#">{{ post.author }}</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>Posted on {{ post.created_at }}</p>

        <hr>

        <!-- Preview Image -->
          {% if post.head_image %}
              <img class="img-fluid rounded" src="{{ post.head_image.url }}" alt="">
          {% endif %}

        <hr>

        <!-- Post Content -->
        <p>{{ post.get_content_markdown | safe }}</p>

        {% if post.attached_file %}
            <a href="{{ post.attached_file.url }}" type="button" class="btn btn-dark" download>첨부 파일 다운로드</a>
            {{ post.get_file_name }}
        {% endif %}

        <hr>
                        {% if post.tags.exists %}
                            <br/>
                            <i class = "fas fa=tags"></i>
                            {% for tag in post.tags.iterator %}
                                <a href = {{ tag.get_absolute_url }}> {{ tag }}</a>
                            {% endfor %}
                            <br/>
                            <br/>
                        {% endif %}
        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            <form id="comment-form" method="Post" action="{{ post.get_absolute_url }}addComment/"> {% csrf_token %}
              <div class="form-group">
                {{ comment_form | crispy }}
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>

        <!-- Single Comment -->
      {% if post.commen_set.exists %}
        {%  for comment in post.comment_set.iterator %}

        <div class="media mb-4" id="{{ comment.pk }}">
{#          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">#}
          <div class="media-body">
            <h5 class="mt-0">{{ comment.author.username }} &nbsp;&nbsp;<small class="text-muted">{{ comment.created_at }}</small>
            </h5>
              <p>{{ comment.content | linebreaks }}</p>
          </div>
        </div>
        {% endfor %}
      {% endif %}

      </div>
    {% endblock %}

blog_main/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    <title>Create Post - blog</title>
{% endblock %}

{% block main_area %}
    <h1>Create Post</h1>

    <form method="post" enctype="multipart/form-data"> {% csrf_token %}
        <table>
            {{ form | crispy }}
        </table>
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
    {{ form.media }}
{% endblock %}

blog_main/blog/templates/blog/post_form_update.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    <title>Update Post - blog</title>
{% endblock %}

{% block main_area %}
    <h1>Update Post</h1>

    <form method="post" enctype="multipart/form-data"> {% csrf_token %}
        <table>
            {{ form | crispy }}
        </table>
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
{% endblock %}

blog_main/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block title %}
    <title>Blog</title>
{% endblock %}

{% block main_area %}
    {% if user.is_authenticated %}
        {% if user.is_superuser or user.is_staff %}
            <a href="/blog/create_post" role="button">Create Post</a>
        {% endif %}
    {% endif %}
                <h1>Blog
                    {%  if category %} in category '{{  category }}' {% endif %}
                    {%  if tag %} with tag '{{ tag }}' {% endif %}
                </h1>

                {% for p in post_list %}
                <!-- Blog Post -->
                <div class="card mb-4">
                    {% if p.head_image %}
                        <img class="card-img-top" src="{{ p.head_image.url }}" alt="Card image cap">
                    {% else %}
                        <img class="card-img-top" src="https://picsum.photos/seed/{{ p.pk }}/800/200" alt="Card image cap">

                    {% endif %}
                    <div class="card-body">
                        <h2 class="card-title">{{ p.title}}</h2>
                        <p class="card-text">{{ p.get_content_markdown | truncatewords_html:30 | safe }}</p>
                        <a href="{{ p.get_absolute_url }}" class="btn btn-primary">Read More &rarr;</a>
                        {% if p.tags.exists %}
                            <br/>
                            <i class = "fas fa=tags"></i>
                            {% for tag in p.tags.iterator %}
                                <a href = {{ tag.get_absolute_url }}> {{ tag }}</a>
                            {% endfor %}
                            <br/>
                            <br/>
                        {% endif %}
                    </div>
                    <div class="card-footer text-muted">
                        Posted on {{ p.created_at}} by
                        <a href="#">{{ p.author }}</a>
                    </div>
                </div>
                {% endfor %}


                <!-- Pagination -->
                <ul class="pagination justify-content-center mb-4">
                    <li class="page-item">
                        <a class="page-link" href="#">&larr; Older</a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Newer &rarr;</a>
                    </li>
                </ul>
{% endblock %}

blog_main/single_pages/templates/single_pages/about_me.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>자기소개</title>
</head>
<body>
    <h1>안녕하세요</h1>
</body>
</html>

blog_main/single_pages/templates/single_pages/landing.html
{% extends 'blog/base.html' %}

{% block title %}
    <title>홈페이지 대문</title>
{% endblock %}
{% block main_area %}
    <h1>대문페이지!</h1>{% endblock %}